<a href="https://colab.research.google.com/github/BishalDas1010/BIT_project_TInyML/blob/main/PAMAP2_Physical_Activity_Monitoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
path ="/content/drive/MyDrive/Dataset_For_Bit/pamap2+physical+activity+monitoring.zip"

In [ ]:
import zipfile



with zipfile.ZipFile(path, "r") as zip_ref:
    zip_ref.extractall("extracted_files")

print("ZIP extracted successfully!")

ZIP extracted successfully!

In [ ]:
import zipfile

pathh ="/content/extracted_files/PAMAP2_Dataset.zip"

with zipfile.ZipFile(pathh, "r") as zip_ref:
    zip_ref.extractall("extracted_files")

print("ZIP extracted successfully!")

ZIP extracted successfully!

In [ ]:
import pandas as pd
df = pd.read_csv("/content/extracted_files/PAMAP2_Dataset/Protocol/subject102.dat", sep=' ', header=None)

In [ ]:
lis = [
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject101.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject105.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject106.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject108.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject109.dat",
]

In [ ]:
lis[1]
df =["df1","df2","df3","df4","df5"]
df_list =[]

In [ ]:
for  i in range(len(lis)):
  df[i] = pd.read_csv(lis[i], sep=' ', header=None)
  df[i].head()
  print(f"${list[i]}")
  print(df[i].shape)
  print(df[i].head())
  df_list.append(df[i])

$list[0]
(376417, 54)
     0   1      2     3        4        5        6        7        8   \
0  8.38   0  104.0  30.0  2.37223  8.60074  3.51048  2.43954  8.76165
1  8.39   0    NaN  30.0  2.18837  8.56560  3.66179  2.39494  8.55081
2  8.40   0    NaN  30.0  2.37357  8.60107  3.54898  2.30514  8.53644
3  8.41   0    NaN  30.0  2.07473  8.52853  3.66021  2.33528  8.53622
4  8.42   0    NaN  30.0  2.22936  8.83122  3.70000  2.23055  8.59741

        9   ...        44        45        46       47       48       49   50  \
0  3.35465  ...  0.008300  0.009250 -0.017580 -61.1888 -38.9599 -58.1438  1.0
1  3.64207  ... -0.006577 -0.004638  0.000368 -59.8479 -38.8919 -58.5253  1.0
2  3.73280  ...  0.003014  0.000148  0.022495 -60.7361 -39.4138 -58.3999  1.0
3  3.73277  ...  0.003175 -0.020301  0.011275 -60.4091 -38.7635 -58.3956  1.0
4  3.76295  ...  0.012698 -0.014303 -0.002823 -61.5199 -39.3879 -58.2694  1.0

    51   52   53
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0

[5 rows x 54 columns]
$list[1]
(374783, 54)
     0   1   2     3        4        5        6        7        8        9   \
0  5.70   0 NaN  34.0  2.22755  9.65418  2.38862  2.31968  9.60752  2.58278
1  5.71   0 NaN  34.0  2.37550  9.57647  2.31412  2.45657  9.62177  2.71852
2  5.72   0 NaN  34.0  2.94208  9.53415  2.32275  2.78876  9.64961  2.76342
3  5.73   0 NaN  34.0  3.47541  9.75837  2.40696  3.33080  9.66073  2.68734
4  5.74   0 NaN  34.0  3.54617  9.83232  2.25382  3.67642  9.71848  2.50565

   ...        44        45        46       47       48       49        50  \
0  ... -0.017907  0.009340  0.050097 -32.7091  31.4772  44.2318  0.255373
1  ... -0.070091  0.002312  0.053832 -33.0782  30.9814  44.5148  0.251163
2  ... -0.084468  0.034249  0.030462 -32.5619  30.6982  44.5169  0.250643
3  ... -0.030789  0.058615  0.055252 -32.8212  30.9690  44.6575  0.250917
4  ... -0.020063  0.020903  0.059653 -33.1869  30.0856  44.5154  0.249631

         51        52        53
0  0.783075  0.084602  0.560732
1  0.785583  0.076319  0.560314
2  0.786419  0.072038  0.559941
3  0.786967  0.071013  0.559179
4  0.786602  0.066861  0.560777

[5 rows x 54 columns]
$list[2]
(361817, 54)
     0   1   2        3        4        5        6        7        8   \
0  5.89   0 NaN  32.6875 -6.39979  2.58932  6.67079 -6.26368  2.57551
1  5.90   0 NaN  32.6875 -6.40246  2.39929  6.63290 -6.20403  2.54483
2  5.91   0 NaN  32.6875 -6.47751  2.47575  6.63152 -6.23328  2.60549
3  5.92   0 NaN  32.6875 -6.32742  2.70155  6.55603 -6.24898  2.62062
4  5.93   0 NaN  32.6875 -6.43250  2.55301  6.82437 -6.23341  2.60548

        9   ...        44        45        46       47       48       49  \
0  6.98619  ...  0.067704  0.001500 -0.011983 -33.6479  27.0146  43.0990
1  6.94089  ...  0.030155  0.025643 -0.007916 -33.7877  27.1478  42.2474
2  6.98609  ...  0.067642 -0.028377  0.004280 -34.8053  27.0702  42.3857
3  6.89547  ...  0.018724  0.012499  0.014775 -33.9116  26.8960  42.1054
4  6.97099  ... -0.009428 -0.012789 -0.010744 -34.0416  27.1609  42.3883

         50        51        52        53
0  0.220967  0.773766  0.285557  0.520497
1  0.221332  0.773236  0.286219  0.520765
2  0.221819  0.773033  0.286287  0.520822
3  0.221836  0.772801  0.287420  0.520535
4  0.221799  0.772786  0.288440  0.520008

[5 rows x 54 columns]
$list[3]
(408031, 54)
     0   1   2        3        4        5         6        7        8   \
0  5.89   0 NaN  33.3125 -9.79760 -1.45670  1.014380 -9.70702 -1.60337
1  5.90   0 NaN  33.3125 -9.91204 -1.41822  0.974050 -9.78262 -1.60285
2  5.91   0 NaN  33.3125 -9.87531 -1.57027  0.975113 -9.78237 -1.57265
3  5.92   0 NaN  33.3125 -9.72175 -1.60870  1.054520 -9.70677 -1.60334
4  5.93   0 NaN  33.3125 -9.79920 -1.49497  0.975999 -9.58657 -1.57408

        9   ...        44        45        46       47       48       49  \
0  1.32098  ... -0.013731  0.010364  0.010731 -35.4550  38.3829 -17.9083
1  1.29085  ...  0.004436 -0.005926 -0.006704 -35.4508  38.2543 -17.7663
2  1.29079  ...  0.022508 -0.002265  0.014646 -35.6984  38.2688 -17.0580
3  1.35118  ... -0.006964  0.035314  0.010982 -34.9492  38.7447 -17.6233
4  1.27549  ... -0.015835 -0.001065 -0.000410 -35.2105  38.8857 -17.9080

         50        51        52        53
0  0.546211  0.370903  0.695334  0.283892
1  0.545806  0.370867  0.695680  0.283872
2  0.545484  0.371607  0.695437  0.284117
3  0.545474  0.372077  0.694859  0.284935
4  0.545810  0.372349  0.694122  0.285732

[5 rows x 54 columns]
$list[4]
(8477, 54)
      0   1      2      3         4        5        6         7        8   \
0  15.47   0  141.0  24.75  -9.98278  2.61759  2.46038 -10.23410  2.69055
1  15.48   0    NaN  24.75  -9.75577  2.46441  2.50279  -9.96280  2.56789
2  15.49   0    NaN  24.75 -10.32720  2.43953  3.45650  -9.96105  2.44737
3  15.50   0    NaN  24.75 -10.99920  2.29537  3.71633 -10.53000  2.45190
4  15.51   0    NaN  24.75 -10.88630  1.83990  3.79653 -11.07110  2.25982

        9   ...        44        45        46       47       48       49  \
0  2.45977  ...  0.714237 -0.235885 -0.341782 -44.2263 -10.2857  7.36341
1  2.58057  ...  0.238571 -0.279597 -0.536439 -44.3354 -10.7931  8.07278
2  2.91305  ... -0.122434 -0.307176 -0.737734 -44.4643 -10.6575  8.21400
3  3.36664  ... -0.347597 -0.349365 -0.938808 -44.2026 -11.1868  7.79004
4  3.73003  ... -0.469862 -0.457702 -1.059880 -43.4225 -11.8694  7.79357

         50        51        52        53
0  0.466904 -0.486197  0.608846 -0.418234
1  0.466590 -0.488971  0.607694 -0.417024
2  0.466964 -0.492189  0.607102 -0.413669
3  0.468730 -0.494896  0.606311 -0.409581
4  0.469978 -0.497652  0.605975 -0.405287

[5 rows x 54 columns]

In [ ]:
#datasetcreate
columns = [
    'timestamp',
    'activityID',
    'heartRate',

    # Hand IMU
    'hand_temperature',
    'hand_acc16_x',
    'hand_acc16_y',
    'hand_acc16_z',
    'hand_acc6_x',
    'hand_acc6_y',
    'hand_acc6_z',
    'hand_gyro_x',
    'hand_gyro_y',
    'hand_gyro_z',
    'hand_mag_x',
    'hand_mag_y',
    'hand_mag_z',
    'hand_orient_1',
    'hand_orient_2',
    'hand_orient_3',
    'hand_orient_4',

    # Chest IMU
    'chest_temperature',
    'chest_acc16_x',
    'chest_acc16_y',
    'chest_acc16_z',
    'chest_acc6_x',
    'chest_acc6_y',
    'chest_acc6_z',
    'chest_gyro_x',
    'chest_gyro_y',
    'chest_gyro_z',
    'chest_mag_x',
    'chest_mag_y',
    'chest_mag_z',
    'chest_orient_1',
    'chest_orient_2',
    'chest_orient_3',
    'chest_orient_4',

    # Ankle IMU
    'ankle_temperature',
    'ankle_acc16_x',
    'ankle_acc16_y',
    'ankle_acc16_z',
    'ankle_acc6_x',
    'ankle_acc6_y',
    'ankle_acc6_z',
    'ankle_gyro_x',
    'ankle_gyro_y',
    'ankle_gyro_z',
    'ankle_mag_x',
    'ankle_mag_y',
    'ankle_mag_z',
    'ankle_orient_1',
    'ankle_orient_2',
    'ankle_orient_3',
    'ankle_orient_4'
]
len(columns)

54

In [ ]:
path=[
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject101.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject102.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject103.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject104.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject105.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject106.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject107.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject108.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject109.dat"
]

In [ ]:
df_list =[]

timestamp
activityID
heartRate
hand IMU data
chest IMU data
ankle IMU data

In [ ]:
import pandas as pd

dataframes = []


for i in range(0,len(path)-1):
    df = pd.read_csv(
        path[i],
        sep=r"\s+",
        header=None,
        names=columns
    )
    dataframes.append(df)
    print(f"Loaded {path[i]}, shape: {df.shape}")


df1 = dataframes[0]
df2 = dataframes[1]
df3 = dataframes[2]
df4 = dataframes[3]
df5 = dataframes[4]
df6 = dataframes[5]
df7 = dataframes[6]
df8 = dataframes[7]
combine_df_y = pd.concat([df1['activityID'], df2['activityID'],df3['activityID'],df4['activityID'],df5['activityID'],df6['activityID'],df7['activityID'],df8['activityID']], ignore_index=True)

print(df1.head())
print(df1.shape)

Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject101.dat, shape: (376417, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject102.dat, shape: (447000, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject103.dat, shape: (252833, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject104.dat, shape: (329576, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject105.dat, shape: (374783, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject106.dat, shape: (361817, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject107.dat, shape: (313599, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject108.dat, shape: (408031, 54)
   timestamp  activityID  heartRate  hand_temperature  hand_acc16_x  \
0       8.38           0      104.0              30.0       2.37223
1       8.39           0        NaN              30.0       2.18837
2       8.40           0        NaN              30.0       2.37357
3       8.41           0        NaN              30.0       2.07473
4       8.42           0        NaN              30.0       2.22936

   hand_acc16_y  hand_acc16_z  hand_acc6_x  hand_acc6_y  hand_acc6_z  ...  \
0       8.60074       3.51048      2.43954      8.76165      3.35465  ...
1       8.56560       3.66179      2.39494      8.55081      3.64207  ...
2       8.60107       3.54898      2.30514      8.53644      3.73280  ...
3       8.52853       3.66021      2.33528      8.53622      3.73277  ...
4       8.83122       3.70000      2.23055      8.59741      3.76295  ...

   ankle_gyro_x  ankle_gyro_y  ankle_gyro_z  ankle_mag_x  ankle_mag_y  \
0      0.008300      0.009250     -0.017580     -61.1888     -38.9599
1     -0.006577     -0.004638      0.000368     -59.8479     -38.8919
2      0.003014      0.000148      0.022495     -60.7361     -39.4138
3      0.003175     -0.020301      0.011275     -60.4091     -38.7635
4      0.012698     -0.014303     -0.002823     -61.5199     -39.3879

   ankle_mag_z  ankle_orient_1  ankle_orient_2  ankle_orient_3  ankle_orient_4
0     -58.1438             1.0             0.0             0.0             0.0
1     -58.5253             1.0             0.0             0.0             0.0
2     -58.3999             1.0             0.0             0.0             0.0
3     -58.3956             1.0             0.0             0.0             0.0
4     -58.2694             1.0             0.0             0.0             0.0

[5 rows x 54 columns]
(376417, 54)

In [ ]:
df1['activityID'].value_counts()

activityID
0     126460
1      27187
6      23575
17     23573
2      23480
16     22941
4      22253
3      21717
5      21265
7      20265
12     15890
13     14899
24     12912
Name: count, dtype: int64

In [ ]:
feature = [
"hand_acc16_x",
"hand_acc16_y",
"hand_acc16_z",
"hand_gyro_x",
"hand_gyro_y",
"hand_gyro_z"
]

In [ ]:
X =df[feature]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408031 entries, 0 to 408030
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   hand_acc16_x  405880 non-null  float64
 1   hand_acc16_y  405880 non-null  float64
 2   hand_acc16_z  405880 non-null  float64
 3   hand_gyro_x   405880 non-null  float64
 4   hand_gyro_y   405880 non-null  float64
 5   hand_gyro_z   405880 non-null  float64
dtypes: float64(6)
memory usage: 18.7 MB

In [ ]:
X.describe()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
count,405880.000000,405880.000000,405880.000000,405880.000000,405880.000000,405880.000000
mean,-5.384200,-4.169108,3.082906,-0.062992,0.059203,-0.033711
std,6.270890,5.924233,3.445358,1.307926,0.908610,1.524781
min,-106.527000,-104.301000,-55.963700,-20.965600,-13.390400,-15.218500
25%,-9.421582,-6.816100,0.867816,-0.314481,-0.167236,-0.268129
50%,-6.244030,-2.863665,2.591190,-0.010368,0.003951,-0.006765
75%,-1.510340,-1.295555,6.141882,0.259672,0.206406,0.246119
max,46.741800,62.033900,116.977000,19.601400,10.432100,14.309000

In [ ]:
combine_df_x = combined_df = pd.concat([df1[feature], df2[feature],df3[feature],df4[feature]], ignore_index=True)

In [ ]:
combine_df_x.head()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
0,2.37223,8.60074,3.51048,-0.092217,0.056812,-0.015845
1,2.18837,8.56560,3.66179,-0.024413,0.047759,0.006474
2,2.37357,8.60107,3.54898,-0.057976,0.032574,-0.006988
3,2.07473,8.52853,3.66021,-0.002352,0.032810,-0.003747
4,2.22936,8.83122,3.70000,0.012269,0.018305,-0.053325

In [ ]:
combine_df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1405826 entries, 0 to 1405825
Data columns (total 6 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   hand_acc16_x  1398907 non-null  float64
 1   hand_acc16_y  1398907 non-null  float64
 2   hand_acc16_z  1398907 non-null  float64
 3   hand_gyro_x   1398907 non-null  float64
 4   hand_gyro_y   1398907 non-null  float64
 5   hand_gyro_z   1398907 non-null  float64
dtypes: float64(6)
memory usage: 64.4 MB

In [ ]:
combine_df_x.head()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
0,2.37223,8.60074,3.51048,-0.092217,0.056812,-0.015845
1,2.18837,8.56560,3.66179,-0.024413,0.047759,0.006474
2,2.37357,8.60107,3.54898,-0.057976,0.032574,-0.006988
3,2.07473,8.52853,3.66021,-0.002352,0.032810,-0.003747
4,2.22936,8.83122,3.70000,0.012269,0.018305,-0.053325

In [ ]:
combine_df_x.describe()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
count,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06
mean,-4.769426e+00,4.892550e+00,3.045617e+00,1.071207e-02,2.546459e-02,-1.027477e-02
std,5.875211e+00,4.216369e+00,3.849335e+00,1.343674e+00,9.055717e-01,1.479819e+00
min,-1.276490e+02,-8.123440e+01,-4.643560e+01,-2.198240e+01,-2.221270e+01,-1.669970e+01
25%,-8.918550e+00,2.534330e+00,9.464640e-01,-3.428740e-01,-2.063870e-01,-2.967750e-01
50%,-5.575380e+00,4.575040e+00,2.994390e+00,-4.198580e-03,7.342450e-03,-5.227380e-03
75%,-6.875805e-01,7.099350e+00,5.842385e+00,3.294555e-01,2.465655e-01,2.726940e-01
max,6.285960e+01,1.068980e+02,1.322950e+02,2.625910e+01,1.698350e+01,1.179370e+01

In [ ]:
combine_df_x.shape

(1405826, 6)

In [ ]:
combine_df_x.describe()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
count,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06
mean,-4.769426e+00,4.892550e+00,3.045617e+00,1.071207e-02,2.546459e-02,-1.027477e-02
std,5.875211e+00,4.216369e+00,3.849335e+00,1.343674e+00,9.055717e-01,1.479819e+00
min,-1.276490e+02,-8.123440e+01,-4.643560e+01,-2.198240e+01,-2.221270e+01,-1.669970e+01
25%,-8.918550e+00,2.534330e+00,9.464640e-01,-3.428740e-01,-2.063870e-01,-2.967750e-01
50%,-5.575380e+00,4.575040e+00,2.994390e+00,-4.198580e-03,7.342450e-03,-5.227380e-03
75%,-6.875805e-01,7.099350e+00,5.842385e+00,3.294555e-01,2.465655e-01,2.726940e-01
max,6.285960e+01,1.068980e+02,1.322950e+02,2.625910e+01,1.698350e+01,1.179370e+01

Y

In [ ]:
target = 'activityID'

In [ ]:
Y =combine_df_y

In [ ]:
Y.unique()
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: activityID, dtype: int64

In [ ]:
Y =Y[ Y !=0]

In [ ]:
Y.unique()

array([ 1,  2,  3, 17, 16, 12, 13,  4,  7,  6,  5, 24])

tacking help from ai
PAMAP2
↓
Select 6 features
↓
Combine subjects
↓
Remove activityID = 0
↓
Normalize
↓
Create windows (100,6)
↓
Train TinyCNN

In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# The variables combine_df_x and Y must have the same indices for alignment
# Combine them temporarily to drop NaNs across both
combined_temp = pd.concat([combine_df_x, Y], axis=1).dropna()

# Separate back into X and Y
X_clean = combined_temp[feature].values
Y_clean = combined_temp['activityID']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_clean)

print(f"Cleaned data shape: {X_scaled.shape}")

Cleaned data shape: (912614, 6)

In [ ]:
X.shape

(408031, 6)

In [ ]:
Y.shape

(1936481,)

In [ ]:
window_size = 100

In [ ]:
X_windows = []
y_windows = []

window_size = 100
# Use X_scaled which was cleaned in wvh1CWx_kPym
limit = len(X_scaled)

for i in range(0, limit - window_size, window_size):
    X_windows.append(X_scaled[i:i+window_size])
    y_windows.append(Y_clean.iloc[i+window_size-1])

X_windows = np.array(X_windows, dtype='float32')
y_windows = np.array(y_windows)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_windows, y_windows, test_size=0.2, random_state=42)

print("Data prepared. X_train shape:", X_train.shape)

Data prepared. X_train shape: (7300, 100, 6)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_windows,
    y_windows,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Input

le = LabelEncoder()
y_train_mapped = le.fit_transform(y_train)
y_test_mapped = le.transform(y_test)

# Re-define model to ensure weight reset
model = Sequential([
    Input(shape=(100, 6)),
    Conv1D(filters=16, kernel_size=3, activation='relu'),
    MaxPooling1D(2),
    Conv1D(filters=32, kernel_size=3, activation='relu'),
    MaxPooling1D(2),
    Flatten(),
    Dense(32, activation='relu'),
    Dense(len(le.classes_), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train,
    y_train_mapped,
    epochs=15,
    batch_size=64,
    validation_data=(X_test, y_test_mapped)
)
model.summary()

# Save the model after training
model.save("har_model.h5")

Epoch 1/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.4568 - loss: 1.6647 - val_accuracy: 0.6616 - val_loss: 1.1659
Epoch 2/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7104 - loss: 1.0019 - val_accuracy: 0.7404 - val_loss: 0.9441
Epoch 3/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7682 - loss: 0.8130 - val_accuracy: 0.7558 - val_loss: 0.8521
Epoch 4/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.7932 - loss: 0.7225 - val_accuracy: 0.7881 - val_loss: 0.7747
Epoch 5/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8105 - loss: 0.6685 - val_accuracy: 0.7809 - val_loss: 0.7673
Epoch 6/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8249 - loss: 0.6149 - val_accuracy: 0.7963 - val_loss: 0.7072
Epoch 7/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8318 - loss: 0.5821 - val_accuracy: 0.8023 - val_loss: 0.7083
Epoch 8/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8433 - loss: 0.5560 - val_accuracy: 0.8028 - val_loss: 0.6829
Epoch 9/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.8489 - loss: 0.5266 - val_accuracy: 0.8072 - val_loss: 0.6890
Epoch 10/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.8493 - loss: 0.5161 - val_accuracy: 0.8127 - val_loss: 0.6639
Epoch 11/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.8564 - loss: 0.4824 - val_accuracy: 0.8176 - val_loss: 0.6705
Epoch 12/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8671 - loss: 0.4628 - val_accuracy: 0.8154 - val_loss: 0.6917
Epoch 13/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8690 - loss: 0.4473 - val_accuracy: 0.8226 - val_loss: 0.6535
Epoch 14/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8726 - loss: 0.4359 - val_accuracy: 0.8198 - val_loss: 0.6573
Epoch 15/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8789 - loss: 0.4180 - val_accuracy: 0.8319 - val_loss: 0.6570

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 98, 16)         │           304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 49, 16)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 47, 32)         │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 23, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 736)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │        23,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           396 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 77,558 (302.96 KB)

 Trainable params: 25,852 (100.98 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 51,706 (201.98 KB)

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
# Use the mapped labels for evaluation to match the model's output layer
loss, acc = model.evaluate(X_test.astype('float32'), y_test_mapped)

print("Accuracy:", acc)

58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8319 - loss: 0.6570
Accuracy: 0.8318729400634766

In [ ]:
sample = X_test[2]

print(sample.shape)

(100, 6)

In [ ]:
sample = np.expand_dims(sample, axis=0)

print(sample.shape)

(1, 100, 6)

In [ ]:
pred = model.predict(sample)

predicted_class = np.argmax(pred)

predicted_activity = le.inverse_transform([predicted_class])

print("Predicted:", predicted_activity[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
Predicted: 3.0

In [ ]:
sample.shape

(1, 100, 6)

In [ ]:
for i in range(5):
    sample = np.expand_dims(X_test[i], axis=0)

    pred = model.predict(sample, verbose=0)

    pred_class = np.argmax(pred)

    predicted = le.inverse_transform([pred_class])[0]

    actual = y_test[i]

    print(f"Sample {i}")
    print("Actual    :", actual)
    print("Predicted :", predicted)
    print()

print()

Sample 0
Actual    : 3.0
Predicted : 3.0

Sample 1
Actual    : 16.0
Predicted : 16.0

Sample 2
Actual    : 3.0
Predicted : 3.0

Sample 3
Actual    : 17.0
Predicted : 17.0

Sample 4
Actual    : 4.0
Predicted : 4.0

In [ ]:
from tensorflow.keras.models import load_model
import numpy as np

model = load_model("har_model.h5")

# Assuming 'sample' is a window of data for prediction, as defined in previous cells
prediction = model.predict(sample)
print(np.argmax(prediction))

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
3

In [ ]:
### New Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv1D, MaxPooling1D, Flatten, Dense,
    Dropout, BatchNormalization, Input
)
import tensorflow as tf

model = Sequential([
    Input(shape=(100, 6)),  # 100 timesteps, 6 channels (ECG, PPG, Temp, Accel x3)

    Conv1D(16, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),

    Conv1D(32, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),
    Dropout(0.3),

    Flatten(),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(len(le.classes_), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train_mapped, epochs=50, batch_size=32,
          validation_data=(X_test, y_test_mapped))

Epoch 1/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.5071 - loss: 1.6108 - val_accuracy: 0.6884 - val_loss: 1.1171
Epoch 2/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6653 - loss: 1.0965 - val_accuracy: 0.7689 - val_loss: 0.8189
Epoch 3/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7278 - loss: 0.9182 - val_accuracy: 0.7798 - val_loss: 0.7428
Epoch 4/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7563 - loss: 0.8342 - val_accuracy: 0.7870 - val_loss: 0.7101
Epoch 5/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.7749 - loss: 0.7718 - val_accuracy: 0.7963 - val_loss: 0.7045
Epoch 6/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7834 - loss: 0.7273 - val_accuracy: 0.7974 - val_loss: 0.6737
Epoch 7/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7949 - loss: 0.6961 - val_accuracy: 0.8078 - val_loss: 0.6560
Epoch 8/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7988 - loss: 0.6761 - val_accuracy: 0.8242 - val_loss: 0.6341
Epoch 9/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8095 - loss: 0.6467 - val_accuracy: 0.8149 - val_loss: 0.6334
Epoch 10/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.8112 - loss: 0.6300 - val_accuracy: 0.8204 - val_loss: 0.6368
Epoch 11/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8062 - loss: 0.6323 - val_accuracy: 0.8149 - val_loss: 0.6176
Epoch 12/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8267 - loss: 0.5888 - val_accuracy: 0.8160 - val_loss: 0.6054
Epoch 13/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8223 - loss: 0.5844 - val_accuracy: 0.8182 - val_loss: 0.6093
Epoch 14/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8301 - loss: 0.5690 - val_accuracy: 0.8176 - val_loss: 0.6145
Epoch 15/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8299 - loss: 0.5632 - val_accuracy: 0.8220 - val_loss: 0.6124
Epoch 16/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8323 - loss: 0.5514 - val_accuracy: 0.8269 - val_loss: 0.6088
Epoch 17/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8256 - loss: 0.5614 - val_accuracy: 0.8220 - val_loss: 0.5990
Epoch 18/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8330 - loss: 0.5519 - val_accuracy: 0.8308 - val_loss: 0.6099
Epoch 19/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8307 - loss: 0.5530 - val_accuracy: 0.8253 - val_loss: 0.5985
Epoch 20/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8445 - loss: 0.5154 - val_accuracy: 0.8258 - val_loss: 0.5969
Epoch 21/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8441 - loss: 0.5149 - val_accuracy: 0.8368 - val_loss: 0.6066
Epoch 22/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8418 - loss: 0.5086 - val_accuracy: 0.8330 - val_loss: 0.5915
Epoch 23/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8430 - loss: 0.5077 - val_accuracy: 0.8193 - val_loss: 0.6170
Epoch 24/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.8459 - loss: 0.5129 - val_accuracy: 0.8286 - val_loss: 0.5942
Epoch 25/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8462 - loss: 0.4884 - val_accuracy: 0.8368 - val_loss: 0.5983
Epoch 26/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8495 - loss: 0.4987 - val_accuracy: 0.8324 - val_loss: 0.5952
Epoch 27/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.8456 - loss: 0.4875 - val_accuracy: 0.8319 - val_loss: 0.6065
Epoch 28/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.8597 - loss: 0.4638 - val_accuracy: 0.8302 - val_loss: 0.5927
Epoch 29/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8514 - loss: 0.4770 - val_accuracy: 0.8395 - val_loss: 0.6038
Epoch 30/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8590 - loss: 0.4549 - val_accuracy: 0.8379 - val_loss: 0.6379
Epoch 31/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8536 - loss: 0.4698 - val_accuracy: 0.8346 - val_loss: 0.6167
Epoch 32/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8549 - loss: 0.4698 - val_accuracy: 0.8346 - val_loss: 0.6011
Epoch 33/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8499 - loss: 0.4657 - val_accuracy: 0.8357 - val_loss: 0.5889
Epoch 34/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8595 - loss: 0.4546 - val_accuracy: 0.8291 - val_loss: 0.6046
Epoch 35/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8563 - loss: 0.4651 - val_accuracy: 0.8280 - val_loss: 0.6185
Epoch 36/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8568 - loss: 0.4556 - val_accuracy: 0.8423 - val_loss: 0.6035
Epoch 37/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8600 - loss: 0.4515 - val_accuracy: 0.8406 - val_loss: 0.5944
Epoch 38/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8522 - loss: 0.4802 - val_accuracy: 0.8297 - val_loss: 0.6221
Epoch 39/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8630 - loss: 0.4354 - val_accuracy: 0.8434 - val_loss: 0.5875
Epoch 40/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8648 - loss: 0.4350 - val_accuracy: 0.8352 - val_loss: 0.5896
Epoch 41/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8630 - loss: 0.4378 - val_accuracy: 0.8346 - val_loss: 0.6263
Epoch 42/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8629 - loss: 0.4458 - val_accuracy: 0.8363 - val_loss: 0.5859
Epoch 43/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8570 - loss: 0.4497 - val_accuracy: 0.8357 - val_loss: 0.6011
Epoch 44/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8621 - loss: 0.4484 - val_accuracy: 0.8335 - val_loss: 0.5944
Epoch 45/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8668 - loss: 0.4259 - val_accuracy: 0.8467 - val_loss: 0.5915
Epoch 46/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8649 - loss: 0.4238 - val_accuracy: 0.8406 - val_loss: 0.5875
Epoch 47/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8723 - loss: 0.4188 - val_accuracy: 0.8368 - val_loss: 0.6030
Epoch 48/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8653 - loss: 0.4225 - val_accuracy: 0.8308 - val_loss: 0.5979
Epoch 49/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8614 - loss: 0.4308 - val_accuracy: 0.8346 - val_loss: 0.5897
Epoch 50/50
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8695 - loss: 0.4197 - val_accuracy: 0.8379 - val_loss: 0.6169

In [ ]:
### New Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv1D, MaxPooling1D, Flatten, Dense,
    Dropout, BatchNormalization, Input
)
import tensorflow as tf

model = Sequential([
    Input(shape=(100, 6)),  # 100 timesteps, 6 channels (ECG, PPG, Temp, Accel x3)

    Conv1D(16, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),

    Conv1D(32, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),
    Dropout(0.3),

    Flatten(),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(len(le.classes_), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train_mapped, epochs=100, batch_size=32,
          validation_data=(X_test, y_test_mapped))

Epoch 1/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.5066 - loss: 1.6362 - val_accuracy: 0.7037 - val_loss: 1.1121
Epoch 2/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6734 - loss: 1.0873 - val_accuracy: 0.7711 - val_loss: 0.8472
Epoch 3/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7240 - loss: 0.9251 - val_accuracy: 0.7809 - val_loss: 0.7653
Epoch 4/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7541 - loss: 0.8438 - val_accuracy: 0.8001 - val_loss: 0.7010
Epoch 5/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.7715 - loss: 0.7696 - val_accuracy: 0.7996 - val_loss: 0.6855
Epoch 6/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.7819 - loss: 0.7308 - val_accuracy: 0.8034 - val_loss: 0.6597
Epoch 7/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7884 - loss: 0.7040 - val_accuracy: 0.8133 - val_loss: 0.6392
Epoch 8/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7989 - loss: 0.6684 - val_accuracy: 0.8127 - val_loss: 0.6498
Epoch 9/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8093 - loss: 0.6420 - val_accuracy: 0.8133 - val_loss: 0.6415
Epoch 10/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8142 - loss: 0.6238 - val_accuracy: 0.8291 - val_loss: 0.6248
Epoch 11/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8197 - loss: 0.5996 - val_accuracy: 0.8226 - val_loss: 0.6361
Epoch 12/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8233 - loss: 0.5839 - val_accuracy: 0.8193 - val_loss: 0.6219
Epoch 13/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8233 - loss: 0.5813 - val_accuracy: 0.8357 - val_loss: 0.6154
Epoch 14/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8296 - loss: 0.5717 - val_accuracy: 0.8187 - val_loss: 0.6193
Epoch 15/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8329 - loss: 0.5510 - val_accuracy: 0.8220 - val_loss: 0.5911
Epoch 16/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8282 - loss: 0.5656 - val_accuracy: 0.8242 - val_loss: 0.6124
Epoch 17/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8363 - loss: 0.5303 - val_accuracy: 0.8198 - val_loss: 0.6172
Epoch 18/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8382 - loss: 0.5293 - val_accuracy: 0.8258 - val_loss: 0.6007
Epoch 19/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8436 - loss: 0.5182 - val_accuracy: 0.8231 - val_loss: 0.6233
Epoch 20/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8444 - loss: 0.5180 - val_accuracy: 0.8302 - val_loss: 0.5897
Epoch 21/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.8475 - loss: 0.4980 - val_accuracy: 0.8335 - val_loss: 0.6012
Epoch 22/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8470 - loss: 0.5052 - val_accuracy: 0.8237 - val_loss: 0.6044
Epoch 23/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8444 - loss: 0.5099 - val_accuracy: 0.8209 - val_loss: 0.6018
Epoch 24/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8471 - loss: 0.4938 - val_accuracy: 0.8275 - val_loss: 0.5923
Epoch 25/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8477 - loss: 0.5012 - val_accuracy: 0.8363 - val_loss: 0.5819
Epoch 26/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8518 - loss: 0.4848 - val_accuracy: 0.8330 - val_loss: 0.5897
Epoch 27/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - accuracy: 0.8555 - loss: 0.4709 - val_accuracy: 0.8352 - val_loss: 0.5788
Epoch 28/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8522 - loss: 0.4720 - val_accuracy: 0.8346 - val_loss: 0.5929
Epoch 29/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8571 - loss: 0.4624 - val_accuracy: 0.8406 - val_loss: 0.5633
Epoch 30/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8599 - loss: 0.4665 - val_accuracy: 0.8352 - val_loss: 0.5890
Epoch 31/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8600 - loss: 0.4502 - val_accuracy: 0.8363 - val_loss: 0.6029
Epoch 32/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8571 - loss: 0.4644 - val_accuracy: 0.8357 - val_loss: 0.5896
Epoch 33/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 8s 36ms/step - accuracy: 0.8566 - loss: 0.4604 - val_accuracy: 0.8357 - val_loss: 0.6245
Epoch 34/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.8570 - loss: 0.4603 - val_accuracy: 0.8406 - val_loss: 0.5835
Epoch 35/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - accuracy: 0.8601 - loss: 0.4481 - val_accuracy: 0.8363 - val_loss: 0.5866
Epoch 36/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8629 - loss: 0.4386 - val_accuracy: 0.8428 - val_loss: 0.5996
Epoch 37/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8627 - loss: 0.4414 - val_accuracy: 0.8324 - val_loss: 0.6015
Epoch 38/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8668 - loss: 0.4364 - val_accuracy: 0.8483 - val_loss: 0.6072
Epoch 39/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8656 - loss: 0.4289 - val_accuracy: 0.8373 - val_loss: 0.6023
Epoch 40/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8588 - loss: 0.4506 - val_accuracy: 0.8406 - val_loss: 0.5786
Epoch 41/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8641 - loss: 0.4365 - val_accuracy: 0.8335 - val_loss: 0.5919
Epoch 42/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8711 - loss: 0.4317 - val_accuracy: 0.8335 - val_loss: 0.5927
Epoch 43/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.8673 - loss: 0.4226 - val_accuracy: 0.8335 - val_loss: 0.6062
Epoch 44/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8637 - loss: 0.4345 - val_accuracy: 0.8379 - val_loss: 0.5806
Epoch 45/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8651 - loss: 0.4314 - val_accuracy: 0.8373 - val_loss: 0.6058
Epoch 46/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8645 - loss: 0.4293 - val_accuracy: 0.8417 - val_loss: 0.5857
Epoch 47/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8693 - loss: 0.4304 - val_accuracy: 0.8406 - val_loss: 0.5932
Epoch 48/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8630 - loss: 0.4237 - val_accuracy: 0.8417 - val_loss: 0.5977
Epoch 49/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8677 - loss: 0.4218 - val_accuracy: 0.8417 - val_loss: 0.5809
Epoch 50/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8732 - loss: 0.4106 - val_accuracy: 0.8488 - val_loss: 0.6018
Epoch 51/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8666 - loss: 0.4133 - val_accuracy: 0.8516 - val_loss: 0.5850
Epoch 52/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8673 - loss: 0.4126 - val_accuracy: 0.8439 - val_loss: 0.6037
Epoch 53/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8621 - loss: 0.4314 - val_accuracy: 0.8439 - val_loss: 0.6078
Epoch 54/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8704 - loss: 0.4162 - val_accuracy: 0.8510 - val_loss: 0.5874
Epoch 55/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8747 - loss: 0.3993 - val_accuracy: 0.8346 - val_loss: 0.6031
Epoch 56/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8700 - loss: 0.4153 - val_accuracy: 0.8412 - val_loss: 0.6138
Epoch 57/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8682 - loss: 0.4135 - val_accuracy: 0.8412 - val_loss: 0.6076
Epoch 58/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8778 - loss: 0.3944 - val_accuracy: 0.8434 - val_loss: 0.6224
Epoch 59/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8740 - loss: 0.3923 - val_accuracy: 0.8461 - val_loss: 0.5951
Epoch 60/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8778 - loss: 0.4001 - val_accuracy: 0.8478 - val_loss: 0.6209
Epoch 61/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.8774 - loss: 0.3917 - val_accuracy: 0.8395 - val_loss: 0.5993
Epoch 62/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8738 - loss: 0.3938 - val_accuracy: 0.8456 - val_loss: 0.6134
Epoch 63/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8759 - loss: 0.3945 - val_accuracy: 0.8456 - val_loss: 0.6198
Epoch 64/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8752 - loss: 0.3909 - val_accuracy: 0.8434 - val_loss: 0.6067
Epoch 65/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8751 - loss: 0.3882 - val_accuracy: 0.8390 - val_loss: 0.6153
Epoch 66/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8771 - loss: 0.3968 - val_accuracy: 0.8379 - val_loss: 0.5977
Epoch 67/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step - accuracy: 0.8732 - loss: 0.4036 - val_accuracy: 0.8510 - val_loss: 0.6163
Epoch 68/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8740 - loss: 0.3919 - val_accuracy: 0.8379 - val_loss: 0.6322
Epoch 69/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8773 - loss: 0.3873 - val_accuracy: 0.8406 - val_loss: 0.6569
Epoch 70/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8784 - loss: 0.3959 - val_accuracy: 0.8406 - val_loss: 0.6284
Epoch 71/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8810 - loss: 0.3765 - val_accuracy: 0.8450 - val_loss: 0.5997
Epoch 72/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8792 - loss: 0.3815 - val_accuracy: 0.8434 - val_loss: 0.6055
Epoch 73/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.8804 - loss: 0.3784 - val_accuracy: 0.8565 - val_loss: 0.6085
Epoch 74/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8829 - loss: 0.3797 - val_accuracy: 0.8373 - val_loss: 0.6186
Epoch 75/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8814 - loss: 0.3744 - val_accuracy: 0.8571 - val_loss: 0.6217
Epoch 76/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8837 - loss: 0.3602 - val_accuracy: 0.8538 - val_loss: 0.6138
Epoch 77/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8800 - loss: 0.3861 - val_accuracy: 0.8379 - val_loss: 0.6190
Epoch 78/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.8852 - loss: 0.3762 - val_accuracy: 0.8483 - val_loss: 0.6259
Epoch 79/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8836 - loss: 0.3725 - val_accuracy: 0.8297 - val_loss: 0.6303
Epoch 80/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8875 - loss: 0.3684 - val_accuracy: 0.8412 - val_loss: 0.6327
Epoch 81/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8855 - loss: 0.3744 - val_accuracy: 0.8532 - val_loss: 0.6370
Epoch 82/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8837 - loss: 0.3709 - val_accuracy: 0.8521 - val_loss: 0.5924
Epoch 83/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8821 - loss: 0.3769 - val_accuracy: 0.8412 - val_loss: 0.6359
Epoch 84/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8834 - loss: 0.3570 - val_accuracy: 0.8488 - val_loss: 0.6271
Epoch 85/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8886 - loss: 0.3629 - val_accuracy: 0.8401 - val_loss: 0.6469
Epoch 86/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8819 - loss: 0.3671 - val_accuracy: 0.8423 - val_loss: 0.6068
Epoch 87/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8840 - loss: 0.3614 - val_accuracy: 0.8505 - val_loss: 0.6153
Epoch 88/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8855 - loss: 0.3654 - val_accuracy: 0.8412 - val_loss: 0.6110
Epoch 89/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8875 - loss: 0.3690 - val_accuracy: 0.8417 - val_loss: 0.6258
Epoch 90/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8858 - loss: 0.3641 - val_accuracy: 0.8445 - val_loss: 0.6092
Epoch 91/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8881 - loss: 0.3583 - val_accuracy: 0.8390 - val_loss: 0.6248
Epoch 92/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8878 - loss: 0.3694 - val_accuracy: 0.8456 - val_loss: 0.6249
Epoch 93/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8797 - loss: 0.3776 - val_accuracy: 0.8428 - val_loss: 0.6218
Epoch 94/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8845 - loss: 0.3700 - val_accuracy: 0.8406 - val_loss: 0.6029
Epoch 95/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8833 - loss: 0.3605 - val_accuracy: 0.8505 - val_loss: 0.6149
Epoch 96/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8862 - loss: 0.3693 - val_accuracy: 0.8373 - val_loss: 0.6187
Epoch 97/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8895 - loss: 0.3596 - val_accuracy: 0.8505 - val_loss: 0.6180
Epoch 98/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8853 - loss: 0.3692 - val_accuracy: 0.8406 - val_loss: 0.6354
Epoch 99/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8921 - loss: 0.3482 - val_accuracy: 0.8352 - val_loss: 0.6313
Epoch 100/100
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8873 - loss: 0.3587 - val_accuracy: 0.8384 - val_loss: 0.6409

In [ ]:
### New Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv1D, MaxPooling1D, Flatten, Dense,
    Dropout, BatchNormalization, Input
)
import tensorflow as tf

model = Sequential([
    Input(shape=(100, 6)),  # 100 timesteps, 6 channels (ECG, PPG, Temp, Accel x3)

    Conv1D(16, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),

    Conv1D(32, kernel_size=3, activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling1D(2),
    Dropout(0.3),

    Flatten(),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(len(le.classes_), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train_mapped, epochs=140, batch_size=32,
          validation_data=(X_test, y_test_mapped))

Epoch 1/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.4904 - loss: 1.6944 - val_accuracy: 0.6742 - val_loss: 1.0924
Epoch 2/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.6555 - loss: 1.1263 - val_accuracy: 0.7596 - val_loss: 0.8523
Epoch 3/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7200 - loss: 0.9381 - val_accuracy: 0.7809 - val_loss: 0.7743
Epoch 4/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.7481 - loss: 0.8478 - val_accuracy: 0.7908 - val_loss: 0.7153
Epoch 5/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7781 - loss: 0.7527 - val_accuracy: 0.8018 - val_loss: 0.6693
Epoch 6/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7825 - loss: 0.7152 - val_accuracy: 0.7990 - val_loss: 0.6838
Epoch 7/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7982 - loss: 0.6766 - val_accuracy: 0.8182 - val_loss: 0.6387
Epoch 8/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8034 - loss: 0.6570 - val_accuracy: 0.8215 - val_loss: 0.6184
Epoch 9/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8134 - loss: 0.6298 - val_accuracy: 0.8078 - val_loss: 0.6440
Epoch 10/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8168 - loss: 0.6022 - val_accuracy: 0.8231 - val_loss: 0.6009
Epoch 11/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.8237 - loss: 0.5906 - val_accuracy: 0.8352 - val_loss: 0.6043
Epoch 12/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8251 - loss: 0.5879 - val_accuracy: 0.8258 - val_loss: 0.6054
Epoch 13/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8242 - loss: 0.5851 - val_accuracy: 0.8286 - val_loss: 0.6403
Epoch 14/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8263 - loss: 0.5647 - val_accuracy: 0.8308 - val_loss: 0.6021
Epoch 15/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8348 - loss: 0.5372 - val_accuracy: 0.8204 - val_loss: 0.6195
Epoch 16/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8379 - loss: 0.5310 - val_accuracy: 0.8258 - val_loss: 0.5986
Epoch 17/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8400 - loss: 0.5191 - val_accuracy: 0.8412 - val_loss: 0.6031
Epoch 18/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8434 - loss: 0.5216 - val_accuracy: 0.8363 - val_loss: 0.5774
Epoch 19/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8393 - loss: 0.5126 - val_accuracy: 0.8324 - val_loss: 0.6001
Epoch 20/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8441 - loss: 0.5255 - val_accuracy: 0.8341 - val_loss: 0.5960
Epoch 21/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8500 - loss: 0.4985 - val_accuracy: 0.8319 - val_loss: 0.6084
Epoch 22/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8401 - loss: 0.5141 - val_accuracy: 0.8357 - val_loss: 0.6021
Epoch 23/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8512 - loss: 0.4963 - val_accuracy: 0.8412 - val_loss: 0.6107
Epoch 24/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8519 - loss: 0.4871 - val_accuracy: 0.8330 - val_loss: 0.6223
Epoch 25/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8514 - loss: 0.4748 - val_accuracy: 0.8417 - val_loss: 0.6080
Epoch 26/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8553 - loss: 0.4485 - val_accuracy: 0.8368 - val_loss: 0.6304
Epoch 27/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8536 - loss: 0.4654 - val_accuracy: 0.8319 - val_loss: 0.5990
Epoch 28/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8590 - loss: 0.4577 - val_accuracy: 0.8363 - val_loss: 0.6153
Epoch 29/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8593 - loss: 0.4544 - val_accuracy: 0.8417 - val_loss: 0.6138
Epoch 30/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8544 - loss: 0.4751 - val_accuracy: 0.8346 - val_loss: 0.5950
Epoch 31/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8533 - loss: 0.4650 - val_accuracy: 0.8308 - val_loss: 0.6135
Epoch 32/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8653 - loss: 0.4416 - val_accuracy: 0.8423 - val_loss: 0.6185
Epoch 33/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8599 - loss: 0.4454 - val_accuracy: 0.8379 - val_loss: 0.6336
Epoch 34/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8622 - loss: 0.4520 - val_accuracy: 0.8346 - val_loss: 0.6038
Epoch 35/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8648 - loss: 0.4382 - val_accuracy: 0.8373 - val_loss: 0.6236
Epoch 36/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8648 - loss: 0.4278 - val_accuracy: 0.8428 - val_loss: 0.5969
Epoch 37/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8667 - loss: 0.4354 - val_accuracy: 0.8335 - val_loss: 0.6219
Epoch 38/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8605 - loss: 0.4451 - val_accuracy: 0.8363 - val_loss: 0.6120
Epoch 39/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8640 - loss: 0.4298 - val_accuracy: 0.8445 - val_loss: 0.6213
Epoch 40/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8590 - loss: 0.4276 - val_accuracy: 0.8423 - val_loss: 0.6123
Epoch 41/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8727 - loss: 0.4133 - val_accuracy: 0.8439 - val_loss: 0.6224
Epoch 42/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8688 - loss: 0.4223 - val_accuracy: 0.8346 - val_loss: 0.6233
Epoch 43/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8678 - loss: 0.4304 - val_accuracy: 0.8406 - val_loss: 0.6262
Epoch 44/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8732 - loss: 0.4136 - val_accuracy: 0.8368 - val_loss: 0.6332
Epoch 45/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8714 - loss: 0.4109 - val_accuracy: 0.8417 - val_loss: 0.6268
Epoch 46/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8645 - loss: 0.4235 - val_accuracy: 0.8450 - val_loss: 0.5942
Epoch 47/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8670 - loss: 0.4209 - val_accuracy: 0.8445 - val_loss: 0.6091
Epoch 48/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8716 - loss: 0.4050 - val_accuracy: 0.8505 - val_loss: 0.6054
Epoch 49/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8759 - loss: 0.4015 - val_accuracy: 0.8384 - val_loss: 0.6491
Epoch 50/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8707 - loss: 0.4097 - val_accuracy: 0.8417 - val_loss: 0.6305
Epoch 51/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8748 - loss: 0.4017 - val_accuracy: 0.8428 - val_loss: 0.6204
Epoch 52/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8700 - loss: 0.4028 - val_accuracy: 0.8434 - val_loss: 0.6227
Epoch 53/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8716 - loss: 0.4015 - val_accuracy: 0.8346 - val_loss: 0.6452
Epoch 54/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8716 - loss: 0.4114 - val_accuracy: 0.8428 - val_loss: 0.6264
Epoch 55/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8701 - loss: 0.4179 - val_accuracy: 0.8406 - val_loss: 0.6455
Epoch 56/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8751 - loss: 0.3915 - val_accuracy: 0.8428 - val_loss: 0.6275
Epoch 57/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8764 - loss: 0.3932 - val_accuracy: 0.8401 - val_loss: 0.6132
Epoch 58/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8753 - loss: 0.3995 - val_accuracy: 0.8395 - val_loss: 0.6069
Epoch 59/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8781 - loss: 0.3860 - val_accuracy: 0.8494 - val_loss: 0.5927
Epoch 60/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8779 - loss: 0.3826 - val_accuracy: 0.8510 - val_loss: 0.6361
Epoch 61/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8785 - loss: 0.3938 - val_accuracy: 0.8390 - val_loss: 0.6240
Epoch 62/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8740 - loss: 0.3933 - val_accuracy: 0.8423 - val_loss: 0.6264
Epoch 63/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8800 - loss: 0.3811 - val_accuracy: 0.8505 - val_loss: 0.6223
Epoch 64/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8732 - loss: 0.4024 - val_accuracy: 0.8450 - val_loss: 0.6433
Epoch 65/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8742 - loss: 0.3867 - val_accuracy: 0.8412 - val_loss: 0.6362
Epoch 66/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8774 - loss: 0.3842 - val_accuracy: 0.8472 - val_loss: 0.6452
Epoch 67/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8740 - loss: 0.3895 - val_accuracy: 0.8467 - val_loss: 0.6194
Epoch 68/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8770 - loss: 0.3810 - val_accuracy: 0.8456 - val_loss: 0.6148
Epoch 69/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8800 - loss: 0.3818 - val_accuracy: 0.8445 - val_loss: 0.6471
Epoch 70/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8730 - loss: 0.3907 - val_accuracy: 0.8395 - val_loss: 0.6736
Epoch 71/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8812 - loss: 0.3886 - val_accuracy: 0.8434 - val_loss: 0.6304
Epoch 72/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8811 - loss: 0.3818 - val_accuracy: 0.8390 - val_loss: 0.6343
Epoch 73/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8822 - loss: 0.3707 - val_accuracy: 0.8483 - val_loss: 0.6311
Epoch 74/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8804 - loss: 0.3738 - val_accuracy: 0.8445 - val_loss: 0.6471
Epoch 75/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8786 - loss: 0.3830 - val_accuracy: 0.8423 - val_loss: 0.6534
Epoch 76/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8775 - loss: 0.3817 - val_accuracy: 0.8373 - val_loss: 0.6445
Epoch 77/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8842 - loss: 0.3579 - val_accuracy: 0.8428 - val_loss: 0.6433
Epoch 78/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8822 - loss: 0.3714 - val_accuracy: 0.8384 - val_loss: 0.6608
Epoch 79/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8840 - loss: 0.3682 - val_accuracy: 0.8467 - val_loss: 0.6484
Epoch 80/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8771 - loss: 0.3814 - val_accuracy: 0.8472 - val_loss: 0.6309
Epoch 81/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8837 - loss: 0.3648 - val_accuracy: 0.8467 - val_loss: 0.6439
Epoch 82/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8790 - loss: 0.3727 - val_accuracy: 0.8494 - val_loss: 0.6354
Epoch 83/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.8795 - loss: 0.3709 - val_accuracy: 0.8401 - val_loss: 0.6558
Epoch 84/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8822 - loss: 0.3676 - val_accuracy: 0.8401 - val_loss: 0.6356
Epoch 85/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8859 - loss: 0.3604 - val_accuracy: 0.8401 - val_loss: 0.6574
Epoch 86/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8833 - loss: 0.3766 - val_accuracy: 0.8554 - val_loss: 0.6530
Epoch 87/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8830 - loss: 0.3650 - val_accuracy: 0.8423 - val_loss: 0.6419
Epoch 88/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.8819 - loss: 0.3615 - val_accuracy: 0.8456 - val_loss: 0.6505
Epoch 89/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8825 - loss: 0.3755 - val_accuracy: 0.8412 - val_loss: 0.6898
Epoch 90/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8838 - loss: 0.3716 - val_accuracy: 0.8450 - val_loss: 0.6525
Epoch 91/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8859 - loss: 0.3530 - val_accuracy: 0.8412 - val_loss: 0.6933
Epoch 92/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8882 - loss: 0.3542 - val_accuracy: 0.8341 - val_loss: 0.6775
Epoch 93/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8841 - loss: 0.3623 - val_accuracy: 0.8428 - val_loss: 0.6390
Epoch 94/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.8808 - loss: 0.3766 - val_accuracy: 0.8384 - val_loss: 0.6514
Epoch 95/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8874 - loss: 0.3519 - val_accuracy: 0.8423 - val_loss: 0.6743
Epoch 96/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8890 - loss: 0.3544 - val_accuracy: 0.8478 - val_loss: 0.6756
Epoch 97/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8866 - loss: 0.3586 - val_accuracy: 0.8423 - val_loss: 0.6476
Epoch 98/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8752 - loss: 0.3944 - val_accuracy: 0.8368 - val_loss: 0.6580
Epoch 99/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8795 - loss: 0.3642 - val_accuracy: 0.8461 - val_loss: 0.6455
Epoch 100/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8862 - loss: 0.3595 - val_accuracy: 0.8494 - val_loss: 0.6534
Epoch 101/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8852 - loss: 0.3550 - val_accuracy: 0.8357 - val_loss: 0.6749
Epoch 102/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8814 - loss: 0.3598 - val_accuracy: 0.8423 - val_loss: 0.6716
Epoch 103/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8907 - loss: 0.3486 - val_accuracy: 0.8423 - val_loss: 0.6615
Epoch 104/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8907 - loss: 0.3464 - val_accuracy: 0.8395 - val_loss: 0.6449
Epoch 105/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8845 - loss: 0.3486 - val_accuracy: 0.8439 - val_loss: 0.6457
Epoch 106/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8838 - loss: 0.3586 - val_accuracy: 0.8412 - val_loss: 0.6472
Epoch 107/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8886 - loss: 0.3473 - val_accuracy: 0.8532 - val_loss: 0.6896
Epoch 108/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8864 - loss: 0.3487 - val_accuracy: 0.8395 - val_loss: 0.6572
Epoch 109/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8895 - loss: 0.3492 - val_accuracy: 0.8412 - val_loss: 0.6585
Epoch 110/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8905 - loss: 0.3415 - val_accuracy: 0.8417 - val_loss: 0.6849
Epoch 111/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8927 - loss: 0.3429 - val_accuracy: 0.8406 - val_loss: 0.6500
Epoch 112/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8922 - loss: 0.3337 - val_accuracy: 0.8390 - val_loss: 0.6749
Epoch 113/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8844 - loss: 0.3566 - val_accuracy: 0.8395 - val_loss: 0.6612
Epoch 114/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8904 - loss: 0.3490 - val_accuracy: 0.8395 - val_loss: 0.6639
Epoch 115/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8934 - loss: 0.3343 - val_accuracy: 0.8472 - val_loss: 0.7024
Epoch 116/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8897 - loss: 0.3490 - val_accuracy: 0.8363 - val_loss: 0.6822
Epoch 117/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.8904 - loss: 0.3366 - val_accuracy: 0.8532 - val_loss: 0.6744
Epoch 118/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8903 - loss: 0.3432 - val_accuracy: 0.8505 - val_loss: 0.6798
Epoch 119/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8805 - loss: 0.3546 - val_accuracy: 0.8412 - val_loss: 0.6783
Epoch 120/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8897 - loss: 0.3453 - val_accuracy: 0.8483 - val_loss: 0.6697
Epoch 121/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8844 - loss: 0.3562 - val_accuracy: 0.8532 - val_loss: 0.6477
Epoch 122/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8958 - loss: 0.3239 - val_accuracy: 0.8532 - val_loss: 0.6774
Epoch 123/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8925 - loss: 0.3438 - val_accuracy: 0.8467 - val_loss: 0.6652
Epoch 124/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8936 - loss: 0.3380 - val_accuracy: 0.8395 - val_loss: 0.7076
Epoch 125/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8916 - loss: 0.3321 - val_accuracy: 0.8461 - val_loss: 0.6595
Epoch 126/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8895 - loss: 0.3426 - val_accuracy: 0.8576 - val_loss: 0.6614
Epoch 127/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8944 - loss: 0.3339 - val_accuracy: 0.8461 - val_loss: 0.6775
Epoch 128/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8971 - loss: 0.3247 - val_accuracy: 0.8450 - val_loss: 0.6776
Epoch 129/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8960 - loss: 0.3348 - val_accuracy: 0.8456 - val_loss: 0.6790
Epoch 130/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8793 - loss: 0.3715 - val_accuracy: 0.8445 - val_loss: 0.6726
Epoch 131/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8881 - loss: 0.3456 - val_accuracy: 0.8417 - val_loss: 0.6974
Epoch 132/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8934 - loss: 0.3320 - val_accuracy: 0.8456 - val_loss: 0.6872
Epoch 133/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8886 - loss: 0.3396 - val_accuracy: 0.8423 - val_loss: 0.6796
Epoch 134/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8967 - loss: 0.3343 - val_accuracy: 0.8423 - val_loss: 0.6860
Epoch 135/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8940 - loss: 0.3346 - val_accuracy: 0.8549 - val_loss: 0.6749
Epoch 136/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8882 - loss: 0.3494 - val_accuracy: 0.8510 - val_loss: 0.6944
Epoch 137/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8873 - loss: 0.3506 - val_accuracy: 0.8560 - val_loss: 0.6878
Epoch 138/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8926 - loss: 0.3408 - val_accuracy: 0.8434 - val_loss: 0.6847
Epoch 139/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8918 - loss: 0.3317 - val_accuracy: 0.8598 - val_loss: 0.6700
Epoch 140/140
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8948 - loss: 0.3283 - val_accuracy: 0.8510 - val_loss: 0.6576

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_6 (Conv1D)               │ (None, 100, 16)        │           304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 100, 16)        │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_6 (MaxPooling1D)  │ (None, 50, 16)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_7 (Conv1D)               │ (None, 50, 32)         │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 50, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_7 (MaxPooling1D)  │ (None, 25, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 25, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 800)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 32)             │        25,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 12)             │           396 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 84,086 (328.46 KB)

 Trainable params: 27,996 (109.36 KB)

 Non-trainable params: 96 (384.00 B)

 Optimizer params: 55,994 (218.73 KB)

In [ ]:
import numpy as np

# Representative dataset for INT8 calibration
def representative_data_gen():
    for sample in X_train[:200]:
        yield [sample.reshape(1, 100, 6).astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open("har_model_int8.tflite", "wb") as f:
    f.write(tflite_model)

print(f"Model size: {len(tflite_model) / 1024:.1f} KB")

In [ ]:
import numpy as np

# Representative dataset for INT8 calibration
def representative_data_gen():
    for sample in X_train[:200]:
        yield [sample.reshape(1, 100, 6).astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

with open("har_model_int8.tflite", "wb") as f:
    f.write(tflite_model)

print(f"Model size: {len(tflite_model) / 1024:.1f} KB")

Saved artifact at '/tmp/tmpgahfzui_'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 100, 6), dtype=tf.float32, name='keras_tensor_84')
Output Type:
  TensorSpec(shape=(None, 12), dtype=tf.float32, name=None)
Captures:
  137006300591120: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300588240: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300587664: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300586704: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300586896: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300589008: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006647974736: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006647975888: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300589968: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300593616: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300587088: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300591888: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300584784: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300578448: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300587280: TensorSpec(shape=(), dtype=tf.resource, name=None)
  137006300587472: TensorSpec(shape=(), dtype=tf.resource, name=None)
Model size: 38.8 KB

/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/convert.py:863: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn(